# Generated by Django 4.0.1 on 2024-05-23 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='clothes_model.category'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothes', to='clothes_model.style'),
        ),
    ]
