# Generated by Django 4.0.1 on 2024-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('product_id', models.IntegerField()),
                ('product_type', models.CharField(choices=[('mobile', 'Mobile'), ('book', 'Book'), ('clothes', 'Clothes')], max_length=20)),
            ],
            options={
                'db_table': 'cart_items',
                'ordering': ['date_added'],
                'unique_together': {('product_id', 'product_type')},
            },
        ),
    ]
